name: Build Android

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Set up Android SDK
      uses: reactivecircus/android-setup-action@v2
      with:
        components: 'build-tools;30.0.3'  # Kullanılan build tools sürümünü belirtin

    - name: Build and Test
      run: |
        ./gradlew assembleDebug  # veya assembleRelease, proje ve gereksinimlere bağlı olarak değişebilir
